/* Game sound cues, generated by piezo. Do not hand-edit.
 *
 * Drop this file into a game and play a cue:
 *
 *   import { play } from './cues.js';
 *   const ctx = new AudioContext();
 *   play(ctx, 'pc-boot');
 *   play(ctx, 'pc-hurt', { gain: 0.5, params: { pitch: 160 } });
 *
 * Every cue is (ctx, t0, out, p) => endTime and schedules everything up front,
 * so firing is cheap and cues overlap freely. Regenerate, do not hand-edit.
 */

export const CUES = {
  "pc-boot": {
    name: "BIOS Boot Beep",
    description: "the single POST beep at power-on",
    gain: 1,
    duration: 0.1427,
    params: {"freq":784,"dur":0.13,"level":0.1},
    // measured: peak -4.68 dBFS, RMS -13.34 dBFS, 0.1427s, centroid 2524 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      tone(p.freq, t0, p.dur, p.level);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-key": {
    name: "Key Click",
    description: "the tick a command entry makes",
    gain: 1,
    duration: 0.0187,
    params: {"freq":1200,"dur":0.006,"level":0.035},
    // measured: peak -22.98 dBFS, RMS -40.21 dBFS, 0.0187s, centroid 2772 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      tone(p.freq, t0, p.dur, p.level);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-move": {
    name: "Footstep",
    description: "a step taken, buzzing because the disc eats the bottom",
    gain: 1,
    duration: 0.036,
    params: {"freq":300,"dur":0.022,"level":0.09},
    // measured: peak -13.5 dBFS, RMS -25.53 dBFS, 0.036s, centroid 2584 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      tone(p.freq, t0, p.dur, p.level);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-bump": {
    name: "Blocked",
    description: "walking into something solid",
    gain: 1,
    duration: 0.1034,
    params: {"freq":140,"dur":0.09,"level":0.13},
    // measured: peak -4.37 dBFS, RMS -19.35 dBFS, 0.1034s, centroid 2674 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      tone(p.freq, t0, p.dur, p.level);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-take": {
    name: "Pick Up",
    description: "two rising notes: something acquired",
    gain: 1,
    duration: 0.1015,
    params: {"freq":659,"interval":1.5,"dur":0.045,"level":0.07},
    // measured: peak -5.04 dBFS, RMS -14.79 dBFS, 0.1015s, centroid 2630 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      tone(p.freq, t0, p.dur, p.level);
      tone(p.freq * p.interval, t0 + p.dur, p.dur, p.level);
      const end = t0 + p.dur * 2;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-hurt": {
    name: "Took Damage",
    description: "a downward sweep, stepped the way a rewritten divisor steps",
    gain: 1,
    duration: 0.1735,
    params: {"from":200,"to":90,"dur":0.16,"level":0.16},
    // measured: peak -4.07 dBFS, RMS -18.07 dBFS, 0.1735s, centroid 2877 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      // A sweep on this hardware is the divisor being rewritten every few ms, so
      // the pitch climbs in audible steps and the level never moves.
      const steps = Math.max(6, Math.round(p.dur / 0.010));
      gate.gain.setValueAtTime(p.level, t0);
      for (let i = 0; i <= steps; i++) {
        osc.frequency.setValueAtTime(pitch(p.from * Math.pow(p.to / p.from, i / steps)), t0 + p.dur * (i / steps));
      }
      gate.gain.setValueAtTime(0, t0 + p.dur);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-bear": {
    name: "Bear Roar",
    description: "a falling sweep into a scribble of random divisors",
    gain: 1,
    duration: 0.6233,
    params: {"from":210,"to":70,"dur":0.34,"grains":9,"level":0.16},
    // measured: peak -3.94 dBFS, RMS -17.99 dBFS, 0.6233s, centroid 2901 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      const steps = Math.max(6, Math.round(p.dur / 0.010));
      gate.gain.setValueAtTime(p.level, t0);
      for (let i = 0; i <= steps; i++) {
        osc.frequency.setValueAtTime(pitch(p.from * Math.pow(p.to / p.from, i / steps)), t0 + p.dur * (i / steps));
      }
      gate.gain.setValueAtTime(0, t0 + p.dur);

      // "Noise": speaker held on while the divisor is scribbled over at random.
      // The randomness is the noise source itself, which is the one place the
      // contract allows it.
      let t = t0 + p.dur;
      gate.gain.setValueAtTime(p.level * 0.7, t);
      for (let i = 0; i < p.grains; i++) {
        osc.frequency.setValueAtTime(pitch(60 + Math.random() * 110), t);
        t += 0.03;
      }
      gate.gain.setValueAtTime(0, t);
      const end = t;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-fire": {
    name: "Fire Crackle",
    description: "gated random divisors: spits and ticks, not a growl",
    gain: 1,
    duration: 0.3101,
    params: {"grains":14,"lo":500,"hi":1500,"step":0.022,"level":0.05},
    // measured: peak -5.99 dBFS, RMS -18.42 dBFS, 0.3101s, centroid 2879 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      let t = t0;
      for (let i = 0; i < p.grains; i++) {
        // 70% duty: the gaps are what make it read as crackle rather than noise.
        if (Math.random() < 0.7) tone(p.lo + Math.random() * Math.max(0, p.hi - p.lo), t, p.step * 0.6, p.level);
        t += p.step;
      }
      const end = t;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-flare": {
    name: "Flare Launch",
    description: "a long rising sweep",
    gain: 1,
    duration: 0.4299,
    params: {"from":320,"to":1900,"dur":0.42,"level":0.05},
    // measured: peak -5.76 dBFS, RMS -15.3 dBFS, 0.4299s, centroid 3261 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      const steps = Math.max(6, Math.round(p.dur / 0.010));
      gate.gain.setValueAtTime(p.level, t0);
      for (let i = 0; i <= steps; i++) {
        osc.frequency.setValueAtTime(pitch(p.from * Math.pow(p.to / p.from, i / steps)), t0 + p.dur * (i / steps));
      }
      gate.gain.setValueAtTime(0, t0 + p.dur);
      const end = t0 + p.dur;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-win": {
    name: "Victory Fanfare",
    description: "C-E-G-C, the reward arpeggio",
    gain: 1,
    duration: 0.6352,
    params: {"root":523,"dur":0.12,"gap":0.008,"level":0.08},
    // measured: peak -4.48 dBFS, RMS -12.49 dBFS, 0.6352s, centroid 2641 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      const ratios = [1, 1.26, 1.5, 2];       // major third, fifth, octave
      let t = t0;
      for (let i = 0; i < ratios.length; i++) {
        const d = i === ratios.length - 1 ? p.dur * 2 : p.dur;   // land on the octave
        tone(p.root * ratios[i], t, d, p.level);
        t += d + p.gap;
      }
      const end = t;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
  "pc-lose": {
    name: "Death March",
    description: "four descending notes, the last one held",
    gain: 1,
    duration: 0.877,
    params: {"root":392,"dur":0.16,"gap":0.008,"level":0.11},
    // measured: peak -4.39 dBFS, RMS -14.44 dBFS, 0.877s, centroid 2661 Hz
    render(ctx, t0, out, p) {
      // IBM PC speaker: one 1-bit square wave through a ~1 inch piezo disc.
      //
      // Source: channel 2 of the 8253 divides a 1.193182 MHz clock by an integer, so
      // the speaker cannot hit an arbitrary pitch -- it snaps to 1193182/n, and the
      // error grows with pitch. One hard square: no volume, no timbre, no second voice.
      //
      // Transducer: the disc has almost no output below ~400 Hz, a loud resonance
      // near 3 kHz and nothing above ~7 kHz. Low notes arrive as harmonics with the
      // fundamental missing, which is why a PC-speaker footstep is a buzz, not a thud.
      const PIT = 1193182;
      const pitch = (f) => PIT / Math.min(65535, Math.max(1, Math.round(PIT / f)));

      const osc = ctx.createOscillator();
      osc.type = 'square';
      osc.frequency.value = 1000;

      const drive = ctx.createGain();               // slam the clipper, so the
      drive.gain.value = 12;                        // band-limited oscillator gets
      const clip = ctx.createWaveShaper();          // real square edges back
      const curve = new Float32Array(1024);
      for (let i = 0; i < curve.length; i++) {
        const x = (i / (curve.length - 1)) * 2 - 1;
        curve[i] = Math.max(-1, Math.min(1, x * 12));
      }
      clip.curve = curve;
      clip.oversample = '4x';

      const gate = ctx.createGain();                // the speaker is a switch: the
      gate.gain.value = 0;                          // hardware cannot fade

      const hp1 = ctx.createBiquadFilter(); hp1.type = 'highpass'; hp1.frequency.value = 380; hp1.Q.value = 0.7;
      const hp2 = ctx.createBiquadFilter(); hp2.type = 'highpass'; hp2.frequency.value = 380; hp2.Q.value = 0.7;
      const res = ctx.createBiquadFilter(); res.type = 'peaking'; res.frequency.value = 3300; res.Q.value = 3.2; res.gain.value = 13;
      const body = ctx.createBiquadFilter(); body.type = 'peaking'; body.frequency.value = 1050; body.Q.value = 1.4; body.gain.value = 5;
      const lp = ctx.createBiquadFilter(); lp.type = 'lowpass'; lp.frequency.value = 7200; lp.Q.value = 0.8;

      const comp = ctx.createDynamicsCompressor();  // a small element, over-driven
      comp.threshold.value = -14; comp.knee.value = 6; comp.ratio.value = 10;
      comp.attack.value = 0.002; comp.release.value = 0.08;

      osc.connect(drive); drive.connect(clip); clip.connect(gate);
      gate.connect(hp1); hp1.connect(hp2); hp2.connect(res); res.connect(body);
      body.connect(lp); lp.connect(comp); comp.connect(out);

      // One note: pitch set, speaker on, speaker off. No ramps anywhere.
      const tone = (f, t, d, v) => {
        osc.frequency.setValueAtTime(pitch(f), t);
        gate.gain.setValueAtTime(v, t);
        gate.gain.setValueAtTime(0, t + d);
      };

      const ratios = [1, 0.84, 0.67, 0.45];
      let t = t0;
      for (let i = 0; i < ratios.length; i++) {
        const d = i === ratios.length - 1 ? p.dur * 2.25 : p.dur;
        tone(p.root * ratios[i], t, d, p.level);
        t += d + p.gap;
      }
      const end = t;
      osc.start(t0);
      osc.stop(end + 0.02);
      return end;

    },
  },
};

export const CUE_NAMES = Object.keys(CUES);

/**
 * Fire a cue.
 * @param {BaseAudioContext} ctx
 * @param {string} name  a key of CUES
 * @param {{when?:number, gain?:number, params?:object, destination?:AudioNode}} [opts]
 * @returns {number} the time the cue finishes
 */
export function play(ctx, name, opts = {}) {
  const cue = CUES[name];
  if (!cue) throw new Error('unknown cue: ' + name);

  const trim = ctx.createGain();
  trim.gain.value = cue.gain * (opts.gain == null ? 1 : opts.gain);
  trim.connect(opts.destination || ctx.destination);

  const t0 = opts.when == null ? ctx.currentTime + 0.01 : opts.when;
  const p = Object.assign({}, cue.params, opts.params);
  let end = t0 + cue.duration;
  try {
    const declared = cue.render(ctx, t0, trim, p);
    if (typeof declared === 'number' && isFinite(declared) && declared >= t0) end = declared;
  } catch (err) {
    trim.disconnect();
    throw err;
  }

  // Release the node graph once the cue is over. Game-side housekeeping only:
  // nothing inside a cue body is allowed to use a timer.
  if (typeof setTimeout === 'function') {
    setTimeout(() => trim.disconnect(), Math.max(0, end - ctx.currentTime) * 1000 + 200);
  }
  return end;
}

export default CUES;
