/* Emits export/cues.js: a self-contained ES module a game can drop in.

   No dependency on this tool, no eval at game runtime -- each cue body is
   written out as a real method, so the shipped file is ordinary JavaScript. */

export function buildModule(cues, { generatedBy = 'piezo', playlists = null, playlist = null } = {}) {
  const entries = cues.map((cue) => {
    const values = {};
    for (const p of cue.params || []) values[p.key] = p.default;
    Object.assign(values, cue.values || {});
    const meta = cue.measure
      ? `    // measured: peak ${cue.measure.peakDb} dBFS, RMS ${cue.measure.rmsDb} dBFS, `
        + `${cue.measure.duration}s, centroid ${cue.measure.centroid} Hz\n`
      : '';
    return `  ${JSON.stringify(cue.id)}: {
    name: ${JSON.stringify(cue.name)},
    description: ${JSON.stringify(cue.description || '')},
    gain: ${num(cue.gain ?? 1)},
    duration: ${num(cue.measure?.duration ?? 0.5)},
    params: ${JSON.stringify(values)},
${meta}    render(ctx, t0, out, p) {
${indent(cue.code, 6)}
    },
  },`;
  }).join('\n');

  const first = cues[0]?.id || 'pc-boot';
  const second = cues[1]?.id || first;
  const file = playlist ? `${playlist.id}.cues.js` : 'cues.js';

  /* A per-playlist module is the same drop-in module scoped to a set, so it
     does not carry a PLAYLISTS map of its own -- it *is* the playlist.

     A whole-library module always carries one, empty or not. A named import of
     something a module does not export is a link-time error that fails the
     whole module, so emitting the map only when there are playlists would
     break `import { PLAYLISTS } from './cues.js'` on a library that happens
     to have none -- including the moment the last playlist is deleted. */
  const rows = (playlists || []).map((pl) => `  ${JSON.stringify(pl.id)}: ${JSON.stringify(pl.cues)},`);
  const sets = playlist ? '' : `
/* The named sets this library is grouped into. A game that only wants one
 * of them can iterate it: PLAYLISTS['ui'].forEach((n) => preload(n)).
 */
export const PLAYLISTS = ${rows.length ? `{\n${rows.join('\n')}\n}` : '{}'};
`;

  // No timestamp in the header: the file is committed, and a generated file
  // that changes on every run is a file nobody can review.
  return `/* Game sound cues, generated by ${generatedBy}. Do not hand-edit.
${playlist ? ` *\n * Playlist: ${comment(playlist.name)}${playlist.description ? ` — ${comment(playlist.description)}` : ''}\n` : ''} *
 * Drop this file into a game and play a cue:
 *
 *   import { play } from './${file}';
 *   const ctx = new AudioContext();
 *   play(ctx, ${JSON.stringify(first)});
 *   play(ctx, ${JSON.stringify(second)}, { gain: 0.5, params: { pitch: 160 } });
 *
 * Every cue is (ctx, t0, out, p) => endTime and schedules everything up front,
 * so firing is cheap and cues overlap freely. Regenerate, do not hand-edit.
 */

export const CUES = {
${entries}
};

export const CUE_NAMES = Object.keys(CUES);
${sets}
/**
 * Fire a cue.
 * @param {BaseAudioContext} ctx
 * @param {string} name  a key of CUES
 * @param {{when?:number, gain?:number, params?:object, destination?:AudioNode}} [opts]
 * @returns {number} the time the cue finishes
 */
export function play(ctx, name, opts = {}) {
  const cue = CUES[name];
  if (!cue) throw new Error('unknown cue: ' + name);

  const trim = ctx.createGain();
  trim.gain.value = cue.gain * (opts.gain == null ? 1 : opts.gain);
  trim.connect(opts.destination || ctx.destination);

  const t0 = opts.when == null ? ctx.currentTime + 0.01 : opts.when;
  const p = Object.assign({}, cue.params, opts.params);
  let end = t0 + cue.duration;
  try {
    const declared = cue.render(ctx, t0, trim, p);
    if (typeof declared === 'number' && isFinite(declared) && declared >= t0) end = declared;
  } catch (err) {
    trim.disconnect();
    throw err;
  }

  // Release the node graph once the cue is over. Game-side housekeeping only:
  // nothing inside a cue body is allowed to use a timer.
  if (typeof setTimeout === 'function') {
    setTimeout(() => trim.disconnect(), Math.max(0, end - ctx.currentTime) * 1000 + 200);
  }
  return end;
}

export default CUES;
`;
}

/* Names and descriptions are user text and go into a block comment, where
   the one sequence that matters is the one that ends it. */
const comment = (s) => String(s).replace(/\*\//g, '*\\/').replace(/[\r\n]+/g, ' ');

const num = (v) => (Number.isFinite(Number(v)) ? Number(Number(v).toFixed(4)) : 0);

function indent(code, spaces) {
  const pad = ' '.repeat(spaces);
  return String(code).split('\n').map((l) => (l.trim() ? pad + l : '')).join('\n');
}
