/* Emits export/cues.js: a self-contained ES module a game can drop in.

   No dependency on this tool, no eval at game runtime -- each cue body is
   written out as a real method, so the shipped file is ordinary JavaScript. */

export function buildModule(cues, { generatedBy = 'piezo' } = {}) {
  const entries = cues.map((cue) => {
    const values = {};
    for (const p of cue.params || []) values[p.key] = p.default;
    Object.assign(values, cue.values || {});
    const meta = cue.measure
      ? `    // measured: peak ${cue.measure.peakDb} dBFS, RMS ${cue.measure.rmsDb} dBFS, `
        + `${cue.measure.duration}s, centroid ${cue.measure.centroid} Hz\n`
      : '';
    return `  ${JSON.stringify(cue.id)}: {
    name: ${JSON.stringify(cue.name)},
    description: ${JSON.stringify(cue.description || '')},
    gain: ${num(cue.gain ?? 1)},
    duration: ${num(cue.measure?.duration ?? 0.5)},
    params: ${JSON.stringify(values)},
${meta}    render(ctx, t0, out, p) {
${indent(cue.code, 6)}
    },
  },`;
  }).join('\n');

  // No timestamp in the header: the file is committed, and a generated file
  // that changes on every run is a file nobody can review.
  return `/* Game sound cues, generated by ${generatedBy}. Do not hand-edit.
 *
 * Drop this file into a game and play a cue:
 *
 *   import { play } from './cues.js';
 *   const ctx = new AudioContext();
 *   play(ctx, 'pc-boot');
 *   play(ctx, 'pc-hurt', { gain: 0.5, params: { pitch: 160 } });
 *
 * Every cue is (ctx, t0, out, p) => endTime and schedules everything up front,
 * so firing is cheap and cues overlap freely. Regenerate, do not hand-edit.
 */

export const CUES = {
${entries}
};

export const CUE_NAMES = Object.keys(CUES);

/**
 * Fire a cue.
 * @param {BaseAudioContext} ctx
 * @param {string} name  a key of CUES
 * @param {{when?:number, gain?:number, params?:object, destination?:AudioNode}} [opts]
 * @returns {number} the time the cue finishes
 */
export function play(ctx, name, opts = {}) {
  const cue = CUES[name];
  if (!cue) throw new Error('unknown cue: ' + name);

  const trim = ctx.createGain();
  trim.gain.value = cue.gain * (opts.gain == null ? 1 : opts.gain);
  trim.connect(opts.destination || ctx.destination);

  const t0 = opts.when == null ? ctx.currentTime + 0.01 : opts.when;
  const p = Object.assign({}, cue.params, opts.params);
  let end = t0 + cue.duration;
  try {
    const declared = cue.render(ctx, t0, trim, p);
    if (typeof declared === 'number' && isFinite(declared) && declared >= t0) end = declared;
  } catch (err) {
    trim.disconnect();
    throw err;
  }

  // Release the node graph once the cue is over. Game-side housekeeping only:
  // nothing inside a cue body is allowed to use a timer.
  if (typeof setTimeout === 'function') {
    setTimeout(() => trim.disconnect(), Math.max(0, end - ctx.currentTime) * 1000 + 200);
  }
  return end;
}

export default CUES;
`;
}

const num = (v) => (Number.isFinite(Number(v)) ? Number(Number(v).toFixed(4)) : 0);

function indent(code, spaces) {
  const pad = ' '.repeat(spaces);
  return String(code).split('\n').map((l) => (l.trim() ? pad + l : '')).join('\n');
}
